root    = "."
tmp_dir = "/tmp/air"

[build]
  cmd         = "go build -o /tmp/air/main ."
  bin         = "/tmp/air/main"
  include_ext = ["go"]
  exclude_dir = ["vendor"]
  delay       = 1000        # ms avant de rebuild après un changement

[log]
  time = true

[color]
  main    = "magenta"
  watcher = "cyan"
  build   = "yellow"
  runner  = "green"

[misc]
  clean_on_exit = true
